channels:
- conda-forge
dependencies:
- python=3.13.1
- pip<=25.2
- pip:
  - mlflow==3.3.2
  - numpy==2.3.2
  - pandas==2.3.2
  - psutil==7.0.0
  - scikit-learn==1.6.1
  - scipy==1.16.1
  - xgboost==3.0.5
name: mlflow-env
